### ISSUE TITLE
source code formatter

### ISSUE THREAD

**Issue by hshiozawa** [siocchi/weekly-app#2]
共通のソースコードのフォーマッターを利用するようにする。

**Comment by iwag** [comment]
どういうストラテジなんだろ。こんな感じ？

1 issue を立てる
2 ブランチ feature/#:id を作る
3 push feature/#:id 
4 master に向けて pull request を出す
5 レビュー者をアサイン
6 レビューしてマージ

ちな自分のところは、

1 適当なbranchを作る
2 push
3 pull request を作る
4 レビューして別の人がマージ

でこれくらいのシンプルなのでいいかなと思った

**Comment by hshiozawa** [comment]
> 1 issue を立てる
> 2 ブランチ feature/#:id を作る
> 3 push feature/#:id
> 4 master に向けて pull request を出す
> 5 レビュー者をアサイン
> 6 レビューしてマージ

まさにそんな感じです。
手間が多いといえば手間がおおいね。

この issue 自体はクローズします。
